package ChatApp;


/**
* ChatApp/ChatOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Monday, 27 March 2017 15:07:03 o'clock CEST
*/

public interface ChatOperations 
{
  void join (ChatApp.ChatCallback objref, String userName);
  void leave (ChatApp.ChatCallback objref);
  void post (ChatApp.ChatCallback objref, String message);
  void list (ChatApp.ChatCallback objref);
  void gomoku (ChatApp.ChatCallback objref, String color);
  void add (ChatApp.ChatCallback objref, int x, int y);
} // interface ChatOperations
