package ChatApp;


/**
* ChatApp/ChatCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Monday, 27 March 2017 15:07:03 o'clock CEST
*/

public interface ChatCallbackOperations 
{
  void callback (String message);
} // interface ChatCallbackOperations
